import '../food_mvvm_pattern/models/food.dart';

List<FoodModel> FOODLIST = <FoodModel>[
  FoodModel("Burger", "KFC", "assets/images/burger.png", 2.99),
  FoodModel("Cheese Dip", "KFC", "assets/images/cheese_dip.png", 4.99),
  FoodModel("Cola", "KFC", "assets/images/cola.png", 1.49),
  FoodModel("Fries", "KFC", "assets/images/fries.png", 2.99),
  FoodModel("Ice Cream", "KFC", "assets/images/ice_cream.png", 9.99),
  FoodModel("Noodle", "KFC", "assets/images/noodles.png", 9.99),
  FoodModel("Sandwich", "KFC", "assets/images/sandwich.png", 9.99),
  FoodModel("Wrap", "KFC", "assets/images/wrap.png", 9.99),
  FoodModel("Burger", "KFC", "assets/images/burger.png", 2.99),
  FoodModel("Cheese Dip", "KFC", "assets/images/cheese_dip.png", 4.99),
  FoodModel("Cola", "Lotteria", "assets/images/cola.png", 1.49),
  FoodModel("Fries", "Lotteria", "assets/images/fries.png", 2.99),
  FoodModel("Ice Cream", "Lotteria", "assets/images/ice_cream.png", 9.99),
  FoodModel("Noodle", "Lotteria", "assets/images/noodles.png", 9.99),
  FoodModel("Sandwich", "Lotteria", "assets/images/sandwich.png", 9.99),
  FoodModel("Wrap", "Lotteria", "assets/images/wrap.png", 9.99),
  FoodModel("Burger", "Lotteria", "assets/images/burger.png", 2.99),
  FoodModel("Cheese Dip", "Lotteria", "assets/images/cheese_dip.png", 4.99),
  FoodModel("Cola", "Lotteria", "assets/images/cola.png", 1.49),
  FoodModel("Fries", "Lotteria", "assets/images/fries.png", 2.99),
  FoodModel("Ice Cream", "Hawkers", "assets/images/ice_cream.png", 9.99),
  FoodModel("Noodle", "Hawkers", "assets/images/noodles.png", 9.99),
  FoodModel("Sandwich", "Hawkers", "assets/images/sandwich.png", 9.99),
  FoodModel("Wrap", "Hawkers", "assets/images/wrap.png", 9.99),
  FoodModel("Ice Cream", "Hawkers", "assets/images/ice_cream.png", 9.99),
  FoodModel("Noodle", "Hawkers", "assets/images/noodles.png", 9.99),
  FoodModel("Sandwich", "Hawkers", "assets/images/sandwich.png", 9.99),
  FoodModel("Wrap", "Hawkers", "assets/images/wrap.png", 9.99),
  FoodModel("Sandwich", "Hawkers", "assets/images/sandwich.png", 9.99),
  FoodModel("Wrap", "Hawkers", "assets/images/wrap.png", 9.99),
];
